apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      restartPolicy: Always
      containers:
        - name: client
          image: joancanellasfontanilles/client

---

apiVersion: v1
kind: Service
metadata:
  name: client-cluster-ip
spec:
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 4200
      targetPort: 4200
